### ISSUE TITLE
dotnet Core support?

### ISSUE THREAD

**Issue by ssinno28** [YellowLineParking/Appy.GitDb#25]
Hello,

Are there any plans to get this supported on dotnet core? It doesn't seem like it would be that difficult to migrate.

Thanks,
Sam

**Comment by Kennethtruyers** [comment]
Hi, thanks for your interest and apologies for the delay in answering.

Yes, we are planning to support dotnet core. We're currently waiting on the dependency on libgit2sharp to release a version that is dotnet core compatible

**Comment by ssinno28** [comment]
Okay awesome, interesting idea going to be using it on a side project, I'll
let you know if I have any issues.

**Comment by Kennethtruyers** [comment]
Cool, please let us know if you need any help. 
Also, if you happen to publish the project or make it open source, we'd very much like to know about it. We'll also mention it here.

**Comment by ssinno28** [comment]
Okay will do
